server:
  port: ${PORT:3002}
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
logging:
  file:
    name: /log/study-api.log
    path: /log
  level:
    com:
      dudgns2824:
        kotlinbackend:
          purchase:
            service:
              MallService: TRACE
      querydsl:
        sql: TRACE
      zaxxer:
        hikari: TRACE
        hikari.HikariConfig: 'DEBUG'
    org:
      hibernate:
        sql: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
